### ISSUE TITLE
replication slot does not exist

### ISSUE THREAD

**Issue by DanielZavacky** [toluaina/pgsync#95]
PGSync version: 1.1.31

Postgres version: 13.1

Elasticsearch version: 7.10.1

Redis version: 6.2.1

Python version: 3.7

Problem Description:
After updating from 1.1.29 version to 1.1.31, pgsync throws the following error: 
```
pgsync_1         | 2021-04-04 22:25:01.642:ERROR:pgsync.base: Exception (psycopg2.errors.UndefinedObject) replication slot "test_items" does not exist
pgsync_1         |
pgsync_1         | [SQL: SELECT xid, data
pgsync_1         | FROM PG_LOGICAL_SLOT_PEEK_CHANGES(%(PG_LOGICAL_SLOT_PEEK_CHANGES_1)s, NULL, NULL)
pgsync_1         | WHERE CAST(CAST(xid AS TEXT) AS BIGINT) < %(param_1)s]
pgsync_1         | [parameters: {'PG_LOGICAL_SLOT_PEEK_CHANGES_1': 'test_items', 'param_1': 3334}]
pgsync_1         | (Background on this error at: http://sqlalche.me/e/14/f405)
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
pgsync_1         |     cursor, statement, parameters, context
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 691, in do_execute
pgsync_1         |     cursor.execute(statement, parameters)
pgsync_1         | psycopg2.errors.UndefinedObject: replication slot "test_items" does not exist
```
If "**items**" is not database table (it is only an index in elasticsearch), "**test_items**" pg replication slot is not created (when I use ```select * from pg_replication_slots```, it is not there). If "**items**" is database table, everything works fine.

NOTE: versions 1.1.29 and 1.1.30 do not throw this error, 1.1.31 and 1.1.32 (latest) do.

**Comment by toluaina** [comment]
Oh yes, you'll need to create it first with the bootstrap command. 

`bootstrap -c /path/to/config`

**Comment by toluaina** [comment]
The case sensitivity should not really matter. Can you connect direty to yout database and run this query.
Also try lowercase names. 

```
SELECT tgname FROM pg_trigger 
WHERE NOT tgisinternal AND tgrelid = 'public.destinationSeasons'::REGCLASS 
AND tgname = 'destinationSeasons_notify' 
```

**Comment by toluaina** [comment]
Can you also try using the latest version on master please.

**Comment by DanielZavacky** [comment]
It looks like case sensitivity does matter. When I tried to run query you posted above, it did't work. I tried a few different forms and it worked only if it was like that: `tgrelid = 'public."destinationSeasons"'::REGCLASS` (table name in quotes)

![image](https://user-images.githubusercontent.com/45260819/114511602-674af780-9c38-11eb-928d-af5d2463ff43.png)

Also `tgname = 'destinationSeasons_notify'` condition seems not working. It returned empty result, I had to change it to `tgname = 'destinationseasons_notify'` (all letters are lowercase)

**Comment by toluaina** [comment]
This is parially addressed in master. Can you please again.  I tried different setting under postgres.conf but got different beheviour from yours.

**Comment by DanielZavacky** [comment]
I tried latest master version and I got new error:
![image](https://user-images.githubusercontent.com/45260819/114841125-c98e2e80-9dd7-11eb-8561-e234e538ad50.png)

**Comment by toluaina** [comment]
Would you mind trying the master branch once again please. I made some significant changes 

Also, if you run into this error again can you please the value of tables on [this](https://github.com/toluaina/pgsync/blob/master/pgsync/base.py#L486) line

print(tables)
print('-' * 100)

**Comment by DanielZavacky** [comment]
Still getting error (result of print(tables) command is at the top in the image)
![image](https://user-images.githubusercontent.com/45260819/115354869-6545e300-a1ba-11eb-9f37-5f77a778b985.png)

**Comment by toluaina** [comment]
Are you running Postgres 13.1?

Also can you connect directly to your db and run these queries below

SELECT * FROM pg_trigger WHERE tgrelid = CAST('destinationseasons' AS regclass)
SELECT * FROM pg_trigger WHERE tgrelid = CAST('destinationSeasons' AS regclass)

\d destinationseasons
\d destinationSeasons

**Comment by toluaina** [comment]
My guess is that you might have created your tables names 
quoted. i.e 

```
CREATE TABLE "destinationSeasons" (
    ....
);
```

I would recommend the vanilla format i.e 

```
CREATE TABLE destinationSeasons (
    ....
);
```

**Comment by LubomirIgonda1** [comment]
@toluaina hi I got the same error here is my env and example code

PGSync version: master branch commit b5ae33f8dbdcd1dadb0397443af8ffb5144342b9
Postgres version: 13.1
Elasticsearch version: 7.10.1
Redis version: 6.2.1
Python version: 3.9.2

````
schema:
[
	{
		"database": "test",
		"index": "my_index",
		"nodes": [
			{
				"table": "myTable",
				"schema": "public",
				"columns": []
			}
		]
	}
]
````

for creating tables I use ORM and default camelCase naming if I create db table without quotes database do not create table with camelCase naming it will transform the table name to lowercase nameming 

![image](https://user-images.githubusercontent.com/9303146/115583058-d4f6c380-a2c9-11eb-8264-86d4175467cb.png)

![image](https://user-images.githubusercontent.com/9303146/115583253-02437180-a2ca-11eb-8a85-8ac423873f4b.png)

I think that the hot fix for this case would be add quotes into this sql statement. In this case fixed the error successfully

![image](https://user-images.githubusercontent.com/9303146/115583627-5a7a7380-a2ca-11eb-8995-453a058c9540.png)

If you see any issue why this is not good idea let me know otherwise I can create PR for this hotfix just let me know

**Comment by toluaina** [comment]
I feel this might solve it here but create other problems elsewhere. I have not found a good way to create a trigger if it is not already present. 
I am starting to thinkc  ecking for trigger existence is not necessary and the original error had another error earlier.

**Comment by toluaina** [comment]
I have removed the trigger check from the master version.
For the original post, it would be useful to see the full traceback logs.

**Comment by DanielZavacky** [comment]
I changed table names as you recommended. I also checked current master version, where you removed trigger_exists function and it works. Issue can be closed, thank you

**Comment by toluaina** [comment]
Closing this.Thanks
